Jeu_Mastermind : main.o Mastermind.o 
	gcc -o Jeu_Mastermind main.o Mastermind.o 

main.o : main.c Mastermind.c Mastermind.h 
	gcc -c -Wall main.c 

Mastermind.o : Mastermind.c Mastermind.h 
	gcc -c -Wall Mastermind.c 